# Generated by Django 4.2.29 on 2026-05-07 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyword_ai', '0001_phase1_content_analysis_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('task_type', models.CharField(choices=[('single_url', 'Single URL Analysis'), ('batch_urls', 'Batch URL Analysis'), ('content_text', 'Content Text Analysis'), ('competitor_analysis', 'Competitor Gap Analysis')], max_length=30)),
                ('parameters', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('progress_percent', models.IntegerField(default=0, help_text='Progress 0-100')),
                ('current_step', models.CharField(blank=True, help_text='Current processing step', max_length=200)),
                ('result_data', models.JSONField(blank=True, default=dict, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('total_urls', models.IntegerField(default=1)),
                ('processed_urls', models.IntegerField(default=0)),
                ('failed_urls', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('session_id', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Analysis Task',
                'verbose_name_plural': 'Analysis Tasks',
                'ordering': ['-created_at'],
            },
        ),
    ]
