# Generated by Django 4.2.29 on 2026-05-07 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keyword_ai', '0002_phase4_async_tasks'),
    ]

    operations = [
        migrations.CreateModel(
            name='ABTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=200)),
                ('test_description', models.TextField(blank=True)),
                ('control_model', models.CharField(max_length=100)),
                ('treatment_model', models.CharField(max_length=100)),
                ('traffic_split_percent', models.IntegerField(default=50)),
                ('control_metrics', models.JSONField(default=dict)),
                ('treatment_metrics', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('stopped', 'Stopped')], default='running', max_length=20)),
                ('winner', models.CharField(blank=True, help_text=' winning model variant', max_length=100)),
                ('confidence_level', models.FloatField(blank=True, help_text='Statistical confidence 0-1', null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'A/B Test',
                'verbose_name_plural': 'A/B Tests',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSessionMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=100)),
                ('total_analyses', models.IntegerField(default=0)),
                ('total_keywords_generated', models.IntegerField(default=0)),
                ('total_feedback_submitted', models.IntegerField(default=0)),
                ('avg_time_on_page', models.IntegerField(blank=True, help_text='Seconds', null=True)),
                ('features_used', models.JSONField(default=list)),
                ('first_activity', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Session Metrics',
                'verbose_name_plural': 'User Session Metrics',
                'ordering': ['-last_activity'],
            },
        ),
        migrations.CreateModel(
            name='ModelPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(db_index=True, max_length=100)),
                ('model_version', models.CharField(max_length=50)),
                ('total_predictions', models.IntegerField(default=0)),
                ('accepted_suggestions', models.IntegerField(default=0)),
                ('rejected_suggestions', models.IntegerField(default=0)),
                ('ignored_suggestions', models.IntegerField(default=0)),
                ('avg_relevance_score', models.FloatField(blank=True, null=True)),
                ('avg_user_rating', models.FloatField(blank=True, null=True)),
                ('precision_at_k', models.JSONField(default=dict, help_text='Precision@K metrics')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Model Performance',
                'verbose_name_plural': 'Model Performances',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['model_name', 'recorded_at'], name='keyword_ai__model_n_4fc38f_idx')],
            },
        ),
        migrations.CreateModel(
            name='KeywordRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=200)),
                ('url', models.URLField(max_length=2000)),
                ('ranking_position', models.IntegerField(blank=True, null=True)),
                ('search_volume', models.IntegerField(blank=True, null=True)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='keyword_ai.keywordopportunity')),
            ],
            options={
                'verbose_name': 'Keyword Ranking',
                'verbose_name_plural': 'Keyword Rankings',
                'ordering': ['-checked_at'],
            },
        ),
    ]
