# Generated by Django 4.2.30 on 2026-05-14 10:08

from django.db import migrations
import pgvector.django.vector


class Migration(migrations.Migration):

    dependencies = [
        ('keyword_ai', '0004_phase6_rag_vector_search'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='contentanalysis',
            new_name='keyword_ai__quality_5fde98_idx',
            old_name='contentanalysis_quality_analyzed_idx',
        ),
        migrations.RenameIndex(
            model_name='contentanalysis',
            new_name='keyword_ai__url_cf195a_idx',
            old_name='contentanalysis_url_idx',
        ),
        migrations.AlterField(
            model_name='contentanalysis',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, help_text='Vector embedding for RAG similarity search', null=True),
        ),
    ]
