# Generated by Django 4.2.30 on 2026-05-19 13:43

from django.db import migrations, models, connection


def vector_to_jsonb(apps, schema_editor):
    if connection.vendor != 'postgresql':
        return
    schema_editor.execute('DROP INDEX IF EXISTS contentanalysis_embedding_idx;')
    schema_editor.execute(
        '''
        ALTER TABLE keyword_ai_contentanalysis
        ALTER COLUMN embedding TYPE jsonb
        USING CASE
            WHEN embedding IS NULL THEN NULL
            ELSE embedding::text::jsonb
        END;
        '''
    )


def jsonb_to_vector(apps, schema_editor):
    if connection.vendor != 'postgresql':
        return
    schema_editor.execute('CREATE EXTENSION IF NOT EXISTS vector;')
    schema_editor.execute(
        '''
        ALTER TABLE keyword_ai_contentanalysis
        ALTER COLUMN embedding TYPE vector(384)
        USING CASE
            WHEN embedding IS NULL THEN NULL
            ELSE embedding::text::vector
        END;
        '''
    )
    schema_editor.execute(
        '''
        CREATE INDEX IF NOT EXISTS contentanalysis_embedding_idx
        ON keyword_ai_contentanalysis
        USING hnsw (embedding vector_cosine_ops)
        WITH (m = 16, ef_construction = 64);
        '''
    )


class Migration(migrations.Migration):

    dependencies = [
        ('keyword_ai', '0005_rename_contentanalysis_quality_analyzed_idx_keyword_ai__quality_5fde98_idx_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(vector_to_jsonb, jsonb_to_vector),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='contentanalysis',
                    name='embedding',
                    field=models.JSONField(blank=True, help_text='Vector embedding list for Pinecone upload', null=True),
                ),
            ],
        ),
    ]
