# Generated by Django 4.2.30 on 2026-05-19 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyword_ai', '0005_rename_contentanalysis_quality_analyzed_idx_keyword_ai__quality_5fde98_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentanalysis',
            name='embedding',
            field=models.JSONField(blank=True, help_text='Vector embedding list for Pinecone upload', null=True),
        ),
    ]
