# Generated by Django 4.2.30 on 2026-05-20 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyword_ai', '0006_sqlite_jsonfield_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentanalysis',
            name='full_text',
            field=models.TextField(blank=True, help_text='Full extracted text content'),
        ),
    ]
