# Generated by Django 4.2.30 on 2026-05-21 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keyword_ai', '0008_add_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='contentanalysis',
            name='kwai_content_date_quality_idx',
        ),
        migrations.RemoveIndex(
            model_name='modelperformance',
            name='kwai_perf_model_date_idx',
        ),
        migrations.RenameIndex(
            model_name='analysistask',
            new_name='keyword_ai__task_id_2e5467_idx',
            old_name='kwai_task_taskid_idx',
        ),
        migrations.RenameIndex(
            model_name='analysistask',
            new_name='keyword_ai__status_5d84a0_idx',
            old_name='kwai_task_status_date_idx',
        ),
        migrations.RenameIndex(
            model_name='analysistask',
            new_name='keyword_ai__session_4dd7e1_idx',
            old_name='kwai_task_session_date_idx',
        ),
        migrations.RenameIndex(
            model_name='keywordopportunity',
            new_name='keyword_ai__content_1aedd7_idx',
            old_name='kwai_opp_content_relevance_idx',
        ),
        migrations.RenameIndex(
            model_name='keywordopportunity',
            new_name='keyword_ai__keyword_8dfa4f_idx',
            old_name='kwai_opp_keyword_type_idx',
        ),
        migrations.RenameIndex(
            model_name='keywordopportunity',
            new_name='keyword_ai__search__dfd3e4_idx',
            old_name='kwai_opp_intent_score_idx',
        ),
        migrations.RenameIndex(
            model_name='keywordopportunity',
            new_name='keyword_ai__priorit_13fe4a_idx',
            old_name='kwai_opp_priority_score_idx',
        ),
        migrations.RenameIndex(
            model_name='suggestionfeedback',
            new_name='keyword_ai__opportu_8cd70f_idx',
            old_name='kwai_fb_opp_time_idx',
        ),
        migrations.RenameIndex(
            model_name='suggestionfeedback',
            new_name='keyword_ai__user_ac_654183_idx',
            old_name='kwai_fb_action_time_idx',
        ),
    ]
