# Generated by Django 4.2.30 on 2026-06-05 15:33

from django.db import migrations, models
import pgvector.django.vector


class Migration(migrations.Migration):

    dependencies = [
        ('keyword_ai', '0009_remove_contentanalysis_kwai_content_date_quality_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abtest',
            name='winner',
            field=models.CharField(blank=True, help_text='Winning model variant', max_length=100),
        ),
        migrations.AlterField(
            model_name='contentanalysis',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, help_text='384-dim sentence transformer embedding for pgvector', null=True),
        ),
        migrations.AlterField(
            model_name='modelperformance',
            name='model_version',
            field=models.CharField(max_length=100),
        ),
    ]
