# Generated by Django 4.2.30 on 2026-06-05 15:33

from django.db import migrations, models, connection
import pgvector.django.vector


def jsonb_to_vector(apps, schema_editor):
    if connection.vendor != 'postgresql':
        return
    schema_editor.execute('CREATE EXTENSION IF NOT EXISTS vector;')
    schema_editor.execute(
        '''
        ALTER TABLE keyword_ai_contentanalysis
        ALTER COLUMN embedding TYPE vector(384)
        USING CASE
            WHEN embedding IS NULL THEN NULL
            ELSE embedding::text::vector
        END;
        '''
    )
    schema_editor.execute(
        '''
        CREATE INDEX IF NOT EXISTS contentanalysis_embedding_idx
        ON keyword_ai_contentanalysis
        USING hnsw (embedding vector_cosine_ops)
        WITH (m = 16, ef_construction = 64);
        '''
    )


def vector_to_jsonb(apps, schema_editor):
    if connection.vendor != 'postgresql':
        return
    schema_editor.execute('DROP INDEX IF EXISTS contentanalysis_embedding_idx;')
    schema_editor.execute(
        '''
        ALTER TABLE keyword_ai_contentanalysis
        ALTER COLUMN embedding TYPE jsonb
        USING CASE
            WHEN embedding IS NULL THEN NULL
            ELSE embedding::text::jsonb
        END;
        '''
    )


class Migration(migrations.Migration):

    dependencies = [
        ('keyword_ai', '0009_remove_contentanalysis_kwai_content_date_quality_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abtest',
            name='winner',
            field=models.CharField(blank=True, help_text='Winning model variant', max_length=100),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(jsonb_to_vector, vector_to_jsonb),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='contentanalysis',
                    name='embedding',
                    field=pgvector.django.vector.VectorField(blank=True, dimensions=384, help_text='384-dim sentence transformer embedding for pgvector', null=True),
                ),
            ],
        ),
        migrations.AlterField(
            model_name='modelperformance',
            name='model_version',
            field=models.CharField(max_length=100),
        ),
    ]
