# Generated by Django 4.2.29 on 2026-03-18 23:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(db_index=True, max_length=300, unique=True)),
                ('source', models.CharField(choices=[('autocomplete', 'Google Autocomplete'), ('user_search', 'User Search'), ('trend_feed', 'Google Trends / Trend Feed'), ('manual', 'Manually Added'), ('keyword_planner', 'Google Keyword Planner'), ('kaggle', 'Kaggle Dataset')], default='autocomplete', max_length=30)),
                ('intent', models.CharField(choices=[('informational', 'Informational'), ('commercial', 'Commercial'), ('transactional', 'Transactional'), ('navigational', 'Navigational'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('trend_score', models.FloatField(default=0.0, help_text='0.0–100.0 trend score from Google Trends')),
                ('search_volume', models.IntegerField(default=0, help_text='Estimated monthly search volume')),
                ('times_suggested', models.IntegerField(default=0, help_text='How many times this was returned as a suggestion')),
                ('times_searched', models.IntegerField(default=0, help_text='How many times a user searched FOR this keyword')),
                ('is_active', models.BooleanField(default=True, help_text='Set False to exclude from training')),
                ('first_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_trend_check', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-trend_score', '-times_searched'],
            },
        ),
        migrations.CreateModel(
            name='ModelTrainingRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('rolled_back', 'Rolled Back')], default='pending', max_length=20)),
                ('trigger', models.CharField(choices=[('scheduled', 'Scheduled (cron)'), ('manual', 'Manually Triggered'), ('threshold', 'New Keywords Threshold'), ('api', 'API Trigger')], default='scheduled', max_length=20)),
                ('keywords_count', models.IntegerField(default=0)),
                ('new_keywords_added', models.IntegerField(default=0)),
                ('pairs_count', models.IntegerField(default=0)),
                ('embedding_dim', models.IntegerField(default=384)),
                ('model_name', models.CharField(default='all-MiniLM-L6-v2', max_length=100)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('faiss_index_path', models.CharField(blank=True, max_length=500)),
                ('keywords_json_path', models.CharField(blank=True, max_length=500)),
                ('embeddings_path', models.CharField(blank=True, max_length=500)),
                ('error_message', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=False, help_text="True = this run's artifacts are currently loaded")),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrendSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trend_score', models.FloatField()),
                ('search_volume', models.IntegerField(default=0)),
                ('snapshot_date', models.DateField(default=django.utils.timezone.now)),
                ('source', models.CharField(default='google_trends', max_length=50)),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='keyword_suggestion.keywordentry')),
            ],
            options={
                'ordering': ['-snapshot_date'],
            },
        ),
        migrations.CreateModel(
            name='KeywordPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co_occurrence_count', models.IntegerField(default=1, help_text='How many times this pair has been seen together')),
                ('relevance_score', models.FloatField(default=0.5, help_text='Manual or computed relevance: 0.0 (low) to 1.0 (high)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('seed_keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_seed', to='keyword_suggestion.keywordentry')),
                ('suggested_keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_suggestion', to='keyword_suggestion.keywordentry')),
            ],
            options={
                'ordering': ['-co_occurrence_count', '-relevance_score'],
            },
        ),
        migrations.AddIndex(
            model_name='keywordentry',
            index=models.Index(fields=['source'], name='keyword_sug_source_a5283c_idx'),
        ),
        migrations.AddIndex(
            model_name='keywordentry',
            index=models.Index(fields=['intent'], name='keyword_sug_intent_e83460_idx'),
        ),
        migrations.AddIndex(
            model_name='keywordentry',
            index=models.Index(fields=['is_active', 'last_seen'], name='keyword_sug_is_acti_56ce1a_idx'),
        ),
        migrations.AddIndex(
            model_name='keywordentry',
            index=models.Index(fields=['trend_score'], name='keyword_sug_trend_s_1ed416_idx'),
        ),
        migrations.AddIndex(
            model_name='trendsnapshot',
            index=models.Index(fields=['keyword', 'snapshot_date'], name='keyword_sug_keyword_b6b021_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='trendsnapshot',
            unique_together={('keyword', 'snapshot_date', 'source')},
        ),
        migrations.AddIndex(
            model_name='keywordpair',
            index=models.Index(fields=['seed_keyword', 'is_active'], name='keyword_sug_seed_ke_897ec7_idx'),
        ),
        migrations.AddIndex(
            model_name='keywordpair',
            index=models.Index(fields=['co_occurrence_count'], name='keyword_sug_co_occu_6327ea_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='keywordpair',
            unique_together={('seed_keyword', 'suggested_keyword')},
        ),
    ]
