"""
Django settings for Project project.

Generated by 'django-admin startproject' using Django 4.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""
import os.path
from pathlib import Path
import django_heroku
import dj_database_url
import os
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
from django.core.checks import messages

BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-j6zzp2rm^v6(m90de2662_$$53&ro8vdmz&g&gg*o#jl9_5@pw'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']
CSRF_TRUSTED_ORIGINS = [
    "https://e551-119-155-204-25.ngrok-free.app",
    "https://d2c9-202-47-51-230.ngrok-free.app",
    # Add any other trusted origins if applicable.
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'SEOAnalyzer',
    'comparative_analysis',
    "keyword_suggestion.apps.KeywordSuggestionConfig",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/


STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = (os.path.join(BASE_DIR, 'static'),)
django_heroku.settings(locals())
# LOCAL
SITE_URL = "http://127.0.0.1:8000"
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = 'moazzamrazaghori@gmail.com'
EMAIL_HOST_PASSWORD = 'ahdbwmrxdpiaxiew'
# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_AGE=300000



MOZ_ACCESS_ID = os.getenv('MOZ_ACCESS_ID')
MOZ_SECRET_KEY = os.getenv('MOZ_SECRET_KEY')
USE_MOZ_API = os.getenv('USE_MOZ_API', 'false').lower() == 'true'
MOZ_API_MONTHLY_LIMIT = int(os.getenv('MOZ_API_MONTHLY_LIMIT', 50))

# OpenAI Configuration (supports both OpenAI and OpenRouter)
OPENAI_API_KEY = os.getenv('OPENAI_API_KEY')
OPENAI_MODEL = os.getenv('OPENAI_MODEL', 'gpt-4o-mini')
USE_OPENROUTER = os.getenv('USE_OPENROUTER', 'false').lower() == 'true'


CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "keyword-suggestions-cache",
    }
}


LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {message}",
            "style": "{",
        }
    },
    "handlers": {
        "console": {"class": "logging.StreamHandler", "formatter": "verbose"}
    },
    "loggers": {
        "keyword_suggestion": {"handlers": ["console"], "level": "DEBUG", "propagate": False},
        "ml_models":          {"handlers": ["console"], "level": "INFO",  "propagate": False},
        "pipeline":           {"handlers": ["console"], "level": "INFO",  "propagate": False},
    },
}

ML_MODELS_DIR      = BASE_DIR / "ml_models"
FAISS_INDEX_PATH   = ML_MODELS_DIR / "faiss_index.bin"
KEYWORDS_JSON_PATH = ML_MODELS_DIR / "keywords.json"



from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {
    # Collect fresh keyword trends every 6 hours
    "collect-trends-every-6h": {
        "task": "pipeline.collect_trends",
        "schedule": crontab(minute=0, hour="*/6"),
    },

    # Smart training check every hour
    "check-and-train-hourly": {
        "task": "pipeline.check_and_train",
        "schedule": crontab(minute=30),   # runs at :30 of every hour
    },

    # Guaranteed full retrain every Sunday at 2 AM
    "full-retrain-weekly": {
        "task": "pipeline.full_retrain",
        "schedule": crontab(minute=0, hour=2, day_of_week="sunday"),
    },
}