# Generated by Django 4.2.30 on 2026-05-19 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('free', 'Free Trial'), ('basic', 'Basic'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], max_length=20, unique=True)),
                ('display_name', models.CharField(max_length=50)),
                ('price_monthly', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('price_yearly', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('has_ai_suggestions', models.BooleanField(default=False)),
                ('has_competitor_analysis', models.BooleanField(default=False)),
                ('has_pdf_export', models.BooleanField(default=False)),
                ('has_api_access', models.BooleanField(default=False)),
                ('has_priority_support', models.BooleanField(default=False)),
                ('max_audits_per_month', models.IntegerField(blank=True, help_text='None = unlimited', null=True)),
                ('max_keywords_per_analysis', models.IntegerField(default=20)),
                ('max_competitors_per_analysis', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('features_list', models.JSONField(default=list, help_text='List of feature descriptions for UI')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Subscription Tier',
                'verbose_name_plural': 'Subscription Tiers',
                'ordering': ['price_monthly'],
            },
        ),
        migrations.CreateModel(
            name='UsageTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audits_used_this_month', models.IntegerField(default=0)),
                ('keywords_generated_this_month', models.IntegerField(default=0)),
                ('competitor_analyses_this_month', models.IntegerField(default=0)),
                ('pdf_exports_this_month', models.IntegerField(default=0)),
                ('free_audit_used', models.BooleanField(default=False)),
                ('free_audit_used_at', models.DateTimeField(blank=True, null=True)),
                ('last_reset_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('usage_history', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usage_tracker', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usage Tracker',
                'verbose_name_plural': 'Usage Trackers',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('trialing', 'Trialing'), ('past_due', 'Past Due'), ('canceled', 'Canceled'), ('unpaid', 'Unpaid'), ('incomplete', 'Incomplete'), ('free_trial_used', 'Free Trial Used')], default='free_trial_used', max_length=20)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=10)),
                ('current_period_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('trial_end', models.DateTimeField(blank=True, null=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=100)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='subscriptions.subscriptiontier')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], max_length=20)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=100)),
                ('stripe_invoice_id', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('subscription', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='subscriptions.subscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment Record',
                'verbose_name_plural': 'Payment Records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ManualPaymentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('sender_name', models.CharField(help_text='Name on bank account', max_length=200)),
                ('sender_account_last4', models.CharField(blank=True, help_text='Last 4 digits of account', max_length=4)),
                ('transaction_reference', models.CharField(blank=True, help_text='Transaction ID or reference number', max_length=100)),
                ('payment_date', models.DateField(help_text='Date payment was sent')),
                ('proof_document', models.FileField(blank=True, help_text='Receipt, screenshot, or proof of transfer', null=True, upload_to='payment_proofs/%Y/%m/')),
                ('notes', models.TextField(blank=True, help_text='Any additional notes from user')),
                ('status', models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified - Activated'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('verification_notes', models.TextField(blank=True, help_text='Admin notes about verification')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_payments', to='subscriptions.subscriptiontier')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_payments', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Manual Payment Submission',
                'verbose_name_plural': 'Manual Payment Submissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeatureAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(max_length=50)),
                ('access_granted', models.BooleanField()),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_access_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feature Access Log',
                'verbose_name_plural': 'Feature Access Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
