# Generated by Django 4.2.30 on 2026-05-21 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_add_performance_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='featureaccesslog',
            new_name='subscriptio_user_id_f090c1_idx',
            old_name='subscr_feaure_user_feat_time_idx',
        ),
        migrations.RenameIndex(
            model_name='manualpaymentsubmission',
            new_name='subscriptio_status_3a2fbd_idx',
            old_name='subscr_manual_status_date_idx',
        ),
        migrations.RenameIndex(
            model_name='manualpaymentsubmission',
            new_name='subscriptio_user_id_a9ca8b_idx',
            old_name='subscr_manual_user_date_idx',
        ),
        migrations.RenameIndex(
            model_name='paymentrecord',
            new_name='subscriptio_user_id_170c83_idx',
            old_name='subscr_payment_user_date_idx',
        ),
        migrations.RenameIndex(
            model_name='paymentrecord',
            new_name='subscriptio_status_054f2b_idx',
            old_name='subscr_payment_status_date_idx',
        ),
        migrations.RenameIndex(
            model_name='subscription',
            new_name='subscriptio_status_16d834_idx',
            old_name='subscr_sub_status_date_idx',
        ),
        migrations.RenameIndex(
            model_name='usagetracker',
            new_name='subscriptio_user_id_cc11b9_idx',
            old_name='subscr_usage_user_reset_idx',
        ),
    ]
